---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-full-access
  namespace: web
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-read-access
  namespace: web
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "watch", "list"]

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-full-access
  namespace: api
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-read-access
  namespace: api
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "watch", "list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-full-access
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-full-access
subjects:
  - kind: Group
    namespace: web
    name: 73a18acb-c65d-4990-a41c-0c39d4a82d37 # webdev Group

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-read-access
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-read-access
subjects:
  - kind: Group
    namespace: web
    name: 4c051f95-127f-4e13-b9e8-d2ed6e0ebea6 # apidev Group

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-full-access
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-full-access
subjects:
  - kind: Group
    namespace: api
    name: 4c051f95-127f-4e13-b9e8-d2ed6e0ebea6 # apidev Group

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-read-access
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-read-access
subjects:
  - kind: Group
    namespace: api
    name: 73a18acb-c65d-4990-a41c-0c39d4a82d37 # webdev Group
