---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  labels:
    app: tripviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
        - name: tripviewer
          image: registryxgn2768.azurecr.io/tripinsights/tripviewer:1.0
          ports:
            - containerPort: 80
          env:
            - name: TRIPS_API_ENDPOINT
              value: http://0.0.0.0
            - name: USERPROFILE_API_ENDPOINT
              value: http://0.0.0.0
