---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  namespace: api
  labels:
    app: userprofile
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: userprofile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
  namespace: api
  labels:
    app: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
        - name: userprofile
          image: registryxgn2768.azurecr.io/tripinsight/userprofile:1.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: secrets-store
              mountPath: /secrets
              readOnly: true
      resource:
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-kvname-user-msi
