---
apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: api
  labels:
    app: trips
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: trips
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-deployment
  namespace: api
  labels:
    app: trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
        - name: trips
          image: registryxgn2768.azurecr.io/tripinsights/trips:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: secrets-store
              mountPath: /secrets
              readOnly: true
      resource:
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-kvname-user-msi
